services:
  app:
    build:
      args:
        - JARFILE=build/libs/MVPBussinesCRM-0.0.1-SNAPSHOT.jar
    container_name: MVPBusinessCRM
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mvpBusinessCRMAPI
      SPRING_DATASOURCE_USERNAME: api_mvpBusinessCRM
      SPRING_DATASOURCE_PASSWORD: qwerty
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15.11-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: api_mvpBusinessCRM
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mvpBusinessCRMAPI
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge