apiVersion: v1
kind: Service
metadata:
  name: mvp-business-crm-service
spec:
  selector:
    app: mvp-business-crm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
