name: Autotests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: mvpBusinessCRMAPI
          POSTGRES_USER: api_mvpBusinessCRM
          POSTGRES_PASSWORD: qwerty
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U api_mvpBusinessCRM -d mvpBusinessCRMAPI"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run gradle build
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon
